# Generated by Django 2.1.5 on 2020-05-27 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_auto_20200527_0710'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addition',
            old_name='element',
            new_name='html',
        ),
        migrations.AddField(
            model_name='addition',
            name='tag',
            field=models.TextField(default=''),
        ),
    ]
