# Generated by Django 2.1.5 on 2020-05-28 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_auto_20200527_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addition',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
